#!/usr/bin/env python3
"""Generate a Vesktop System24 palette from Quickshell Material colors.

This script reads the Material You color palette generated by Quickshell's
wallpaper pipeline and produces a CSS file that overrides System24 theme
variables. The result keeps Vesktop in sync with the current wallpaper.

IMPORTANT: The generated CSS uses higher specificity to override system24's
default colors which are defined in :root.
"""

from __future__ import annotations

import json
import os
from colorsys import rgb_to_hls, hls_to_rgb
from pathlib import Path
from typing import Dict, Tuple


COLOR_SOURCE = Path(
    os.environ.get(
        "QUICKSHELL_COLORS_JSON",
        "~/.local/state/quickshell/user/generated/colors.json",
    )
).expanduser()

OUTPUT_FILE = Path(
    os.environ.get(
        "SYSTEM24_PALETTE_CSS",
        "~/.config/vesktop/themes/system24.theme.css",
    )
).expanduser()

# Template for the full theme file
THEME_TEMPLATE = '''/**
 * @name ii-niri Material
 * @description Material Design Discord theme with Material You colors.
 * @author refact0r (system24 base), ii-niri (Material adaptation)
 * @version 2.2.0
 * @source https://github.com/end-4/ii-niri
 */

@import url('https://refact0r.github.io/system24/build/system24.css');
@import url('https://fonts.googleapis.com/css2?family=Oxanium:wght@300;400;500;600;700&display=swap');

body {{
    --font: 'Oxanium';
    --code-font: 'Oxanium';
    font-weight: 400;
    letter-spacing: -0.02ch;
    --gap: 8px;
    --divider-thickness: 2px;
    --border-thickness: 0px;
    --border-hover-transition: 0.15s ease;
    --animations: on;
    --list-item-transition: 0.12s ease;
    --dms-icon-svg-transition: 0.2s ease;
    --top-bar-height: var(--gap);
    --top-bar-button-position: titlebar;
    --top-bar-title-position: off;
    --subtle-top-bar-title: off;
    --custom-window-controls: off;
    --window-control-size: 14px;
    --custom-dms-icon: off;
    --dms-icon-svg-size: 80%;
    --dms-icon-color-before: var(--text-0);
    --dms-icon-color-after: var(--text-0);
    --custom-dms-background: color;
    --dms-background-color: var(--accent-2);
    --background-image: off;
    --transparency-tweaks: off;
    --remove-bg-layer: off;
    --panel-blur: off;
    --blur-amount: 0px;
    --bg-floating: var(--bg-1);
    --small-user-panel: on;
    --unrounding: off;
    --custom-spotify-bar: on;
    --ascii-titles: off;
    --ascii-loader: off;
    --panel-labels: off;
    --label-color: var(--text-4);
    --label-font-weight: 500;
}}

/* Material You Palette - Auto-generated */
{palette_css}

/* Material Design System */
html {{ font-size: 16px !important; }}

.guilds__2b93a, .wrapper_fea3ef {{ width: 52px !important; }}
.wrapper_d281dd, .childWrapper__01b9c, .childWrapper_a6ce15 {{
    width: 36px !important; height: 36px !important; border-radius: 12px !important;
}}
.wrapper_d281dd:hover, .childWrapper__01b9c:hover {{ border-radius: 10px !important; }}
.listItem__48528 {{ width: 44px !important; height: 44px !important; margin: 0 0 2px 0 !important; }}
.pill_c3735b {{ left: 0 !important; width: 4px !important; }}
.pill_c3735b .item_c96c45 {{
    width: 3px !important; border-radius: 0 3px 3px 0 !important; background: var(--accent-2) !important;
}}
.tutorialContainer_ff5f24 .childWrapper__01b9c,
.tutorialContainer_ff5f24 .wrapper_d281dd {{ background: var(--accent-2) !important; }}
.tutorialContainer_ff5f24 svg, .tutorialContainer_ff5f24 path {{
    fill: var(--text-0) !important; color: var(--text-0) !important;
}}
.expandedFolderBackground__1bec6 {{ border-radius: 12px !important; background: var(--bg-2) !important; }}
.containerDefault_ae2ea4, .containerDefault__3187b {{
    border-radius: 8px !important; margin: 1px 8px !important; padding: 6px 8px !important;
}}
.name_d8bfb3, .channelName__4d7e3 {{ font-size: 13px !important; }}
.containerDefault__321f3 {{ padding: 16px 8px 4px !important; }}
.name__4eb92 {{ font-size: 11px !important; font-weight: 600 !important; letter-spacing: 0.02em !important; }}
.member_aa4760, .memberInner_aa4760 {{ border-radius: 8px !important; margin: 1px 8px !important; }}
.message_ccca67 {{ border-radius: 8px !important; }}
.cozy_f5c119 {{ padding: 0.2rem 0.75rem !important; }}
.scrollableContainer__33e06 {{ border-radius: 12px !important; }}
.button_dd4f85, .lookFilled_dd4f85 {{ border-radius: 20px !important; }}
.lookOutlined_dd4f85 {{ border-radius: 8px !important; }}
.input_f8bc55, .inputDefault__80165 {{ border-radius: 8px !important; }}
.searchBar__8f956 {{ border-radius: 8px !important; }}
.popout_c5b389, .modal_d3e7d4, .root_f9a4c9 {{
    border-radius: 12px !important; box-shadow: 0 4px 16px rgba(0, 0, 0, 0.2) !important;
}}
.menu_dc52c6 {{ border-radius: 8px !important; padding: 4px !important; }}
.item_a0 {{ border-radius: 6px !important; }}
.tooltip_b6c360 {{ border-radius: 6px !important; }}
.avatar_b2ca13, .wrapper__3ed10 {{ border-radius: 50% !important; }}
.panels_a4d4d9 {{ padding: 0 6px 6px !important; }}
.container__93316 {{ border-radius: 8px !important; }}
::-webkit-scrollbar {{ width: 4px !important; height: 4px !important; }}
::-webkit-scrollbar-thumb {{ border-radius: 2px !important; background: var(--text-5) !important; }}
::-webkit-scrollbar-thumb:hover {{ background: var(--text-4) !important; }}
::-webkit-scrollbar-track {{ background: transparent !important; }}
.contentRegion__3d1e4 {{ border-radius: 12px 0 0 12px !important; }}
.card_dc5ddd {{ border-radius: 8px !important; }}
.emojiPicker_b50b99 {{ border-radius: 12px !important; }}
.scroller__3d071, .thin_eed6a8 {{ border: none !important; }}
.divider__01aed {{ margin: 8px 0 !important; height: 1px !important; }}

/* Number badges - notification counts */
.numberBadge__50328 {{
    background: var(--accent-2) !important;
    color: var(--text-0) !important;
}}

/* Mention badge */
.mentionsBadge__436a7 {{
    background: var(--accent-2) !important;
    color: var(--text-0) !important;
}}

/* Typing indicator */
.dots_c64498 {{
    color: var(--accent-2) !important;
}}

/* Unread message divider */
[class*="divider"][class*="isUnread"],
[class*="divider"][class*="isUnread"]::before,
[class*="divider"][class*="isUnread"]::after {{
    background-color: var(--accent-2) !important;
    border-color: var(--accent-2) !important;
}}
[class*="unreadPill"] {{
    background: var(--accent-2) !important;
    color: var(--text-0) !important;
}}

/* NEW badge text - the span inside unreadMentionsBar */
[class*="unreadMentionsBar"] > span[class*="text"] {{
    color: var(--text-0) !important;
}}
'''


def _ensure_parent(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)


def _load_colors() -> Dict[str, str]:
    if not COLOR_SOURCE.exists():
        raise FileNotFoundError(
            f"Material colors file not found: {COLOR_SOURCE}. "
            "Ensure switchwall.sh has been executed successfully."
        )
    with COLOR_SOURCE.open("r", encoding="utf-8") as fh:
        data = json.load(fh)
    return {k: v.lower() for k, v in data.items()}


def _hex_to_rgb(color: str) -> Tuple[int, int, int]:
    color = color.lstrip("#")
    return tuple(int(color[i : i + 2], 16) for i in range(0, 6, 2))


def _rgb_to_hex(rgb) -> str:
    r, g, b = (max(0, min(int(round(v)), 255)) for v in rgb)
    return f"#{r:02x}{g:02x}{b:02x}"


def _mix(color_a: str, color_b: str, weight: float) -> str:
    ra, ga, ba = _hex_to_rgb(color_a)
    rb, gb, bb = _hex_to_rgb(color_b)
    mixed = (
        ra * (1 - weight) + rb * weight,
        ga * (1 - weight) + gb * weight,
        ba * (1 - weight) + bb * weight,
    )
    return _rgb_to_hex(mixed)


def _adjust_lightness(color: str, delta: float) -> str:
    r, g, b = (c / 255.0 for c in _hex_to_rgb(color))
    h, l, s = rgb_to_hls(r, g, b)
    l = max(0.0, min(1.0, l + delta))
    r2, g2, b2 = hls_to_rgb(h, l, s)
    return _rgb_to_hex((r2 * 255, g2 * 255, b2 * 255))


def _rgba(color: str, alpha: float) -> str:
    r, g, b = _hex_to_rgb(color)
    return f"rgba({r}, {g}, {b}, {alpha:.2f})"


def _build_palette(colors: Dict[str, str]) -> Dict[str, str]:
    """Build the complete system24 color palette from Material You colors."""
    primary = colors["primary"]
    secondary = colors["secondary"]
    tertiary = colors["tertiary"]
    error = colors["error"]
    surface = colors["surface"]
    surface_low = colors["surface_container_low"]
    surface_std = colors["surface_container"]
    surface_high = colors["surface_container_high"]
    surface_highest = colors["surface_container_highest"]
    outline = colors["outline"]
    on_surface = colors["on_surface"]
    on_surface_variant = colors["on_surface_variant"]
    on_primary = colors["on_primary"]

    palette: Dict[str, str] = {}

    # Enable custom colors
    palette["--colors"] = "on"

    # === TEXT COLORS ===
    # --text-0: text on colored elements (like buttons)
    palette["--text-0"] = on_primary
    # --text-1: bright white text
    palette["--text-1"] = on_surface
    # --text-2: headings and important text
    palette["--text-2"] = _mix(on_surface, on_surface_variant, 0.2)
    # --text-3: normal text
    palette["--text-3"] = _mix(on_surface, on_surface_variant, 0.4)
    # --text-4: icon buttons and channels
    palette["--text-4"] = on_surface_variant
    # --text-5: muted channels/chats and timestamps
    palette["--text-5"] = outline

    # === BACKGROUND COLORS ===
    # --bg-4: main background (darkest)
    palette["--bg-4"] = surface
    # --bg-3: spacing, secondary elements
    palette["--bg-3"] = surface_low
    # --bg-2: dark buttons
    palette["--bg-2"] = surface_std
    # --bg-1: dark buttons when clicked
    palette["--bg-1"] = surface_high
    # --bg-floating: floating panels
    palette["--bg-floating"] = surface_highest

    # === INTERACTION STATES ===
    palette["--hover"] = _rgba(primary, 0.10)
    palette["--active"] = _rgba(primary, 0.20)
    palette["--active-2"] = _rgba(primary, 0.30)
    palette["--message-hover"] = _rgba(primary, 0.08)

    # === ACCENT COLORS (based on primary) ===
    palette["--accent-1"] = _adjust_lightness(primary, 0.10)
    palette["--accent-2"] = primary
    palette["--accent-3"] = _adjust_lightness(primary, -0.05)
    palette["--accent-4"] = _adjust_lightness(primary, -0.10)
    palette["--accent-5"] = _adjust_lightness(primary, -0.15)
    palette["--accent-new"] = primary  # Use accent color instead of error for NEW badge

    # === MENTION/REPLY GRADIENTS ===
    palette["--mention"] = (
        f"linear-gradient(to right, "
        f"color-mix(in hsl, {primary}, transparent 70%) 40%, transparent)"
    )
    palette["--mention-hover"] = (
        f"linear-gradient(to right, "
        f"color-mix(in hsl, {primary}, transparent 85%) 40%, transparent)"
    )
    palette["--reply"] = (
        f"linear-gradient(to right, "
        f"color-mix(in hsl, {on_surface_variant}, transparent 85%) 40%, transparent)"
    )
    palette["--reply-hover"] = (
        f"linear-gradient(to right, "
        f"color-mix(in hsl, {on_surface_variant}, transparent 92%) 40%, transparent)"
    )

    # === STATUS COLORS ===
    palette["--online"] = tertiary
    palette["--dnd"] = error
    palette["--idle"] = secondary
    palette["--streaming"] = _adjust_lightness(tertiary, 0.10)
    palette["--offline"] = on_surface_variant

    # === BORDER COLORS ===
    palette["--border-light"] = _rgba(outline, 0.15)
    palette["--border"] = _rgba(outline, 0.30)
    palette["--border-hover"] = primary
    palette["--button-border"] = _rgba(outline, 0.12)

    # === BASE COLOR LADDERS ===
    # These are used throughout system24 for various UI elements
    
    def make_ladder(base: str) -> list:
        """Create 5-step color ladder from base color."""
        return [
            _adjust_lightness(base, 0.15),
            _adjust_lightness(base, 0.08),
            base,
            _adjust_lightness(base, -0.08),
            _adjust_lightness(base, -0.15),
        ]

    # Red ladder (from error color)
    for i, color in enumerate(make_ladder(error), 1):
        palette[f"--red-{i}"] = color

    # Green ladder (from tertiary - usually green-ish)
    for i, color in enumerate(make_ladder(tertiary), 1):
        palette[f"--green-{i}"] = color

    # Blue ladder (from secondary)
    for i, color in enumerate(make_ladder(secondary), 1):
        palette[f"--blue-{i}"] = color

    # Yellow ladder (mix of primary and tertiary for warm tone)
    yellow_base = _mix(primary, tertiary, 0.3)
    yellow_base = _adjust_lightness(yellow_base, 0.05)
    for i, color in enumerate(make_ladder(yellow_base), 1):
        palette[f"--yellow-{i}"] = color

    # Purple ladder (mix of primary and secondary)
    purple_base = _mix(primary, secondary, 0.5)
    for i, color in enumerate(make_ladder(purple_base), 1):
        palette[f"--purple-{i}"] = color

    # Orange ladder (warmer version of primary)
    orange_base = _mix(primary, error, 0.3)
    for i, color in enumerate(make_ladder(orange_base), 1):
        palette[f"--orange-{i}"] = color

    # === DISCORD BRAND OVERRIDES ===
    # These override Discord's default blurple with our accent
    palette["--brand-360"] = _adjust_lightness(primary, 0.08)
    palette["--brand-400"] = _adjust_lightness(primary, 0.04)
    palette["--brand-500"] = primary
    palette["--brand-560"] = _adjust_lightness(primary, -0.06)
    palette["--brand-600"] = _adjust_lightness(primary, -0.12)

    return palette


def _write_palette(palette: Dict[str, str]) -> None:
    """Write the complete theme file with embedded palette."""
    _ensure_parent(OUTPUT_FILE)
    
    # Build palette CSS block
    palette_lines = [":root:root {"]
    for key in sorted(palette.keys()):
        palette_lines.append(f"    {key}: {palette[key]};")
    palette_lines.append("}")
    palette_css = "\n".join(palette_lines)
    
    # Generate full theme with embedded palette
    content = THEME_TEMPLATE.format(palette_css=palette_css)
    
    with OUTPUT_FILE.open("w", encoding="utf-8") as fh:
        fh.write(content)
    
    print(f"Generated: {OUTPUT_FILE}")


def main() -> None:
    try:
        colors = _load_colors()
    except FileNotFoundError as exc:
        print(f"Error: {exc}")
        return

    palette = _build_palette(colors)
    _write_palette(palette)


if __name__ == "__main__":
    main()
