#!/usr/bin/env python3
"""Generate a Vesktop System24 palette from Quickshell Material colors.

This script reads the Material You color palette generated by Quickshell's
wallpaper pipeline and produces a CSS file that overrides System24 theme
variables. The result keeps Vesktop in sync with the current wallpaper.
"""

from __future__ import annotations

import json
import os
from colorsys import rgb_to_hls, hls_to_rgb
from pathlib import Path
from typing import Dict, Iterable, Tuple


COLOR_SOURCE = Path(
    os.environ.get(
        "QUICKSHELL_COLORS_JSON",
        "~/.local/state/quickshell/user/generated/colors.json",
    )
).expanduser()

OUTPUT_FILE = Path(
    os.environ.get(
        "SYSTEM24_PALETTE_CSS",
        "~/.config/vesktop/themes/system24-palette.css",
    )
).expanduser()


def _ensure_parent(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)


def _load_colors() -> Dict[str, str]:
    if not COLOR_SOURCE.exists():
        raise FileNotFoundError(
            f"Material colors file not found: {COLOR_SOURCE}. "
            "Ensure switchwall.sh has been executed successfully."
        )
    with COLOR_SOURCE.open("r", encoding="utf-8") as fh:
        data = json.load(fh)
    return {k: v.lower() for k, v in data.items()}


def _hex_to_rgb(color: str) -> Tuple[int, int, int]:
    color = color.lstrip("#")
    return tuple(int(color[i : i + 2], 16) for i in range(0, 6, 2))


def _rgb_to_hex(rgb: Iterable[float]) -> str:
    r, g, b = (max(0, min(int(round(v)), 255)) for v in rgb)
    return f"#{r:02x}{g:02x}{b:02x}"


def _mix(color_a: str, color_b: str, weight: float) -> str:
    ra, ga, ba = _hex_to_rgb(color_a)
    rb, gb, bb = _hex_to_rgb(color_b)
    mixed = (
        ra * (1 - weight) + rb * weight,
        ga * (1 - weight) + gb * weight,
        ba * (1 - weight) + bb * weight,
    )
    return _rgb_to_hex(mixed)


def _adjust_lightness(color: str, delta: float) -> str:
    r, g, b = (c / 255.0 for c in _hex_to_rgb(color))
    h, l, s = rgb_to_hls(r, g, b)
    l = max(0.0, min(1.0, l + delta))
    r2, g2, b2 = hls_to_rgb(h, l, s)
    return _rgb_to_hex((r2 * 255, g2 * 255, b2 * 255))


def _rgba(color: str, alpha: float) -> str:
    r, g, b = _hex_to_rgb(color)
    return f"rgba({r}, {g}, {b}, {alpha:.3f})"


def _build_palette(colors: Dict[str, str]) -> Dict[str, str]:
    primary = colors["primary"]
    secondary = colors["secondary"]
    tertiary = colors["tertiary"]
    error = colors["error"]
    surface = colors["surface"]
    surface_low = colors["surface_container_low"]
    surface_std = colors["surface_container"]
    surface_high = colors["surface_container_high"]
    surface_highest = colors["surface_container_highest"]
    outline = colors["outline"]
    on_surface = colors["on_surface"]
    on_surface_variant = colors["on_surface_variant"]
    on_primary = colors["on_primary"]
    on_secondary = colors["on_secondary"]
    on_tertiary = colors["on_tertiary"]

    palette: Dict[str, str] = {"--colors": "on"}

    # Text hierarchy
    palette["--text-0"] = on_primary
    palette["--text-1"] = on_surface
    palette["--text-2"] = _mix(on_surface, on_surface_variant, 0.35)
    palette["--text-3"] = on_surface_variant
    palette["--text-4"] = _mix(on_surface_variant, outline, 0.4)
    palette["--text-5"] = outline

    # Background stack
    palette["--bg-4"] = surface
    palette["--bg-3"] = surface_low
    palette["--bg-2"] = surface_std
    palette["--bg-1"] = surface_high
    palette["--bg-floating"] = surface_highest

    # State overlays
    palette["--hover"] = _rgba(primary, 0.12)
    palette["--active"] = _rgba(primary, 0.20)
    palette["--active-2"] = _rgba(primary, 0.32)
    palette["--message-hover"] = palette["--hover"]

    # Mentions / replies
    palette["--mention"] = (
        "linear-gradient(to right, "
        f"color-mix(in oklab, {primary} 30%, transparent) 40%, transparent)"
    )
    palette["--mention-hover"] = (
        "linear-gradient(to right, "
        f"color-mix(in oklab, {primary} 18%, transparent) 40%, transparent)"
    )
    palette["--reply"] = (
        "linear-gradient(to right, "
        f"color-mix(in oklab, {on_surface} 16%, transparent) 40%, transparent)"
    )
    palette["--reply-hover"] = (
        "linear-gradient(to right, "
        f"color-mix(in oklab, {on_surface} 10%, transparent) 40%, transparent)"
    )

    # Accent ladder based on primary
    palette["--accent-1"] = _adjust_lightness(primary, 0.08)
    palette["--accent-2"] = primary
    palette["--accent-3"] = _adjust_lightness(primary, -0.04)
    palette["--accent-4"] = _adjust_lightness(primary, -0.08)
    palette["--accent-5"] = _adjust_lightness(primary, -0.12)
    palette["--accent-new"] = error

    # Status colors
    palette["--online"] = tertiary
    palette["--dnd"] = error
    palette["--idle"] = secondary
    palette["--streaming"] = _adjust_lightness(tertiary, 0.12)
    palette["--offline"] = palette["--text-4"]

    # Border colors
    palette["--border-light"] = _rgba(outline, 0.24)
    palette["--border"] = _rgba(outline, 0.48)
    palette["--border-hover"] = palette["--accent-2"]
    palette["--button-border"] = _rgba(outline, 0.18)

    # Base color ladders derived from core hues
    def ladder(base: str) -> Tuple[str, ...]:
        return (
            _adjust_lightness(base, 0.16),
            _adjust_lightness(base, 0.08),
            base,
            _adjust_lightness(base, -0.08),
            _adjust_lightness(base, -0.16),
        )

    red_ladder = ladder(error)
    green_ladder = ladder(tertiary)
    blue_ladder = ladder(secondary)
    purple_ladder = ladder(_mix(primary, tertiary, 0.5))
    orange_ladder = ladder(primary)

    for idx, value in enumerate(red_ladder, start=1):
        palette[f"--red-{idx}"] = value
    for idx, value in enumerate(green_ladder, start=1):
        palette[f"--green-{idx}"] = value
    for idx, value in enumerate(blue_ladder, start=1):
        palette[f"--blue-{idx}"] = value
    for idx, value in enumerate(purple_ladder, start=1):
        palette[f"--purple-{idx}"] = value
    for idx, value in enumerate(orange_ladder, start=1):
        palette[f"--orange-{idx}"] = value

    return palette


def _write_palette(palette: Dict[str, str]) -> None:
    _ensure_parent(OUTPUT_FILE)
    lines = [
        "/* Auto-generated by system24_palette.py — do not edit manually */",
        ":root {",
    ]

    for key in sorted(palette.keys()):
        lines.append(f"    {key}: {palette[key]};")

    lines.append("}")
    lines.append("")

    with OUTPUT_FILE.open("w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))


def main() -> None:
    try:
        colors = _load_colors()
    except FileNotFoundError as exc:
        print(exc)
        return

    palette = _build_palette(colors)
    _write_palette(palette)


if __name__ == "__main__":
    main()
